name: Changesets

on:
  push:
    branches:
      - main

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      changesets: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create and Publish Versions
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  sync-gh-releases:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Read from CHANGELOG
        uses: actions/github-script@v7
        env:
          CHANGESETS: ${{ needs.version.outputs.changesets }}
        with:
          script: |
            const title = process.env.CHANGESETS;
            console.error(title ?? 'N/A', typeof title);

